function section_d1_plotting(yNumericVector,xAnalytic,zAnalytic)
% Input: yNumericVector:   y state vector with all [x(t), dx(t)/dt, z(t), dz(t)/dt]
%        components. Was generated by ODE computer solver.
%        xAnalytic:        x(t) derived analyticly.
%        zAnalytic:        z(t) same.
% Output: None. Generate at figure #1 plots and save it.

figure();

xNumeric = yNumericVector(:,1);
zNumeric = yNumericVector(:,3);

plot(xNumeric,zNumeric)

hold on 
plot(xAnalytic,zAnalytic,'--')

title 'fig1: Numeric vs Analytic'
grid on
xlabel 'x [m]'
ylabel 'z [m]'
legend('Numeric','Analytic')
axis equal

shg
savefig 'fig1'

end